<?php

namespace Drupal\baseball_migration\Plugin\migrate\source;

use Drupal\migrate\Plugin\migrate\source\SqlBase;
use Drupal\migrate\Row;

/**
 * Source plugin for baseball players.
 *
 * @MigrateSource(
 *   id = "baseball_player"
 * )
 */
class BaseballPlayer extends SqlBase {

  /**
   * {@inheritdoc}
   */

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 *
 * The migration we're processing in this place is "dmeblog_d7_node_type".
 */
function dmeblog_migrate_migrate_dmeblog_d7_node_type_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  // Skip all node types that are not in our list.
  $node_types = ['blog_post'];
  if (!in_array($row->getSourceProperty('type'), $node_types)) {
    throw new MigrateSkipRowException('', TRUE);
  }
}